/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DockerOptions {
  socketPath?: string
  url?: string
  sslKey?: string
  sslCert?: string
  sslCa?: string
}
export declare class Docker {
  constructor(options?: DockerOptions | undefined | null)
  version(): Promise<Buffer>
}
